### ISSUE TITLE
East Ardougne General Store Fix

### ISSUE THREAD

**Issue by Tarzandan** [Odel/vscape#10]
"shopId": 2,
    "name": "Aemad's Adventuring Supplies",
    "items": [
      {
        "id": 227,
        "count": 500
      },
      {
        "id": 1265,
        "count": 2
      },
      {
        "id": 1349,
        "count": 2
      },
      {
        "id": 2142,
        "count": 2
      },
      {
        "id": 591,
        "count": 2
      },
      {
        "id": 1759,
        "count": 30
      },
      {
        "id": 882,
        "count": 500
      },
      {
        "id": 955,
        "count": 20
      },
      {
        "id": 972,
        "count": 50
      },
      {
        "id": 947,
        "count": 2
      }
    ],

**Comment by Odel** [comment]
Fixed, closing, ids were off a bit on a couple (the noted version is the id + 1)
