### ISSUE TITLE
test bad words case-insensitive

### ISSUE THREAD

**Issue by henksteen** [Odel/vscape#2]
in model.players.Player.java line ~1526 change
>if(YellMsg.indexOf(Constants.bad[i]) >= 0)

into
>if(YellMsg.toLowerCase().contains(Constants.bad[i]))

since right now you can type it with arbitrary capitalisation to bypass the filtering.
also "flavius" can be removed from *bad*, right?

**Comment by Odel** [comment]
Fixed, closing.
