### ISSUE TITLE
Issue in Pest Control

### ISSUE THREAD

**Issue by NipploniusOfTyana** [Odel/vscape#62]
For the past day now, things have been spawning a bit wonky and the portals have been offset by 45 degrees at times, and some monsters, specifically ones in pest control do not register damage. I'm rather unsure where to start on this, as I went to Pestcontrol.java and it seemed to all be in order. Unless the code at lines 64 through 68:

"private PortalData(int shieldId, int normalId, int x, int y, String name) {
65			    this.shieldId = shieldId;
66			    this.normalId = normalId;
67			    this.x = x;
68			    this.y = y;

Are causing issues due to an unforseen ambiguity in lines 67 and 68* (Despite [this.variable] being a specific command, and it's main purpose is to reduce ambiguity)? I don't see how this could be simply because these issues weren't happening, and I highly doubt some minor parameter changes in the variables Pickles changed would cause such an issue in the code by just changing some numbers that had nothing to do with imposing an object onto the landscape. 

P.s

I honestly haven't touched Java in forever, and I am aware that I'm probably wasting your time by having you read my hypothesis on why the portals spawn weird. . Though, the fact that the portals have been spawning wonky remains and etc. the same.

**Comment by Pickles-** [comment]
the this keyword stands for a specific instance of the PortalData enum member. When you say this.x = x, you are initializing the PortalData member's x integer to the one specified to it in the enum. This part isn't causing any sort of issue. I'll look into the rest of the problems however.
